csv_generator/csv_generator/urls.py
from django.contrib import admin
from django.contrib.auth import views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from main.views import SchemaList

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', SchemaList.as_view()),
    path('accounts/login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('schemas/', include('main.urls', namespace='main')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

csv_generator/main/urls.py
from django.urls import path
from main.views import SchemaList, SchemaCreate, SchemaEdit, SchemaDelete, DatasetList, create_dataset

app_name = 'main'

urlpatterns = [
    path('list_schemas/', SchemaList.as_view(), name='list_schemas'),
    path('create_schema/', SchemaCreate.as_view(), name='create_schema'),
    path('edit_schema/<int:pk>/', SchemaEdit.as_view(), name='edit_schema'),
    path('delete_schema/<int:pk>/', SchemaDelete.as_view(), name='delete_schema'),
    path('list_datasets/<int:pk>/', DatasetList.as_view(), name='list_datasets'),
    path('create_dataset/', create_dataset, name='create_dataset'),
]

csv_generator/main/models.py
from django.db import models
from django.urls import reverse


class Schema(models.Model):
    COMMA = 'CM'
    TAB = 'TB'
    SPACE = 'SP'
    COLON = 'CL'
    SEMICOLON = 'SC'
    DELIMITERS = (
        (COMMA, 'Comma (,)'),
        (TAB, 'Tabulation ( )'),
        (SPACE, 'Space ( )'),
        (COLON, 'Colon (:)'),
        (SEMICOLON, 'Semicolon (;)'),
    )

    QUOTE = 'QT'
    DOUBLE_QUOTE = 'DQ'
    QUOTES = (
        (QUOTE, 'Quote (\')'),
        (DOUBLE_QUOTE, 'Double-quote (")'),
    )
    name = models.CharField(max_length=30, unique=True)
    delimiter = models.CharField(max_length=2, choices=DELIMITERS, default=COMMA)
    quotes = models.CharField(max_length=2, choices=QUOTES, default=DOUBLE_QUOTE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def get_absolute_url(self):
        return reverse('main:list_schemas')


class SchemaDetails(models.Model):
    FULL_NAME = 'FN'
    JOB = 'JB'
    EMAIL = 'EM'
    PHONE_NUMBER = 'PN'
    DATE = 'DT'
    TYPES = (
        (FULL_NAME, 'Full name'),
        (JOB, 'Job'),
        (EMAIL, 'E-mail'),
        (PHONE_NUMBER, 'Phone number'),
        (DATE, 'Date'),
    )
    name = models.CharField(max_length=20)
    type = models.CharField(max_length=2, choices=TYPES, default=None, blank=False)
    order = models.PositiveSmallIntegerField()
    schema = models.ForeignKey(Schema, on_delete=models.CASCADE)


class Dataset(models.Model):
    file = models.FileField(upload_to='', blank=True)
    task_id = models.CharField(max_length=50)
    schema = models.ForeignKey(Schema, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

csv_generator/main/forms.py
from django import forms

from main.models import Schema, SchemaDetails


class SchemaForm(forms.ModelForm):
    class Meta:
        model = Schema
        fields = ('name', 'delimiter', 'quotes',)


SchemaDetailsFormSet = forms.inlineformset_factory(Schema, SchemaDetails, fields=('name', 'type', 'order',), extra=1)


class DatasetForm(forms.Form):
    class Meta:
        rows = forms.IntegerField()

    # def is_valid(self):
    #     if self.rows > 0:
    #         return super(DatasetForm, self).is_valid()
    #     else:
    #         return False

csv_generator/main/views.py
import boto3
from botocore.client import Config
from celery.result import AsyncResult
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db import transaction
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView

from csv_generator.settings import S3_BUCKET, AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_S3_SIGNATURE_VERSION, \
    REGION_NAME
from main.forms import SchemaForm, SchemaDetailsFormSet, DatasetForm
from main.models import Schema, Dataset
from main.tasks import generate_data


class SchemaList(LoginRequiredMixin, ListView):
    model = Schema
    template_name = 'main/list_schemas.html'
    fields = ['pk', 'name', 'updated_at']


class SchemaCreate(CreateView):
    model = Schema
    template_name = 'main/schema_form.html'
    form_class = SchemaForm

    def get_context_data(self, **kwargs):
        context = super(SchemaCreate, self).get_context_data(**kwargs)
        if self.request.POST:
            context['form'] = SchemaForm(self.request.POST, instance=self.object)
            context['schema_details_form'] = SchemaDetailsFormSet(self.request.POST, instance=self.object)
        else:
            context['form'] = SchemaForm(instance=self.object)
            context['schema_details_form'] = SchemaDetailsFormSet(instance=self.object)
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        schema_details_form = context['schema_details_form']
        with transaction.atomic():
            self.object = form.save()
            if schema_details_form.is_valid():
                schema_details_form.instance = self.object
                schema_details_form.save()
        return super(SchemaCreate, self).form_valid(form)


class SchemaEdit(LoginRequiredMixin, UpdateView):
    model = Schema
    template_name = 'main/schema_form.html'
    form_class = SchemaForm

    def get_context_data(self, **kwargs):
        context = super(SchemaEdit, self).get_context_data(**kwargs)
        if self.request.POST:
            context['form'] = SchemaForm(self.request.POST, instance=self.object)
            context['schema_details_form'] = SchemaDetailsFormSet(self.request.POST, instance=self.object)
        else:
            context['form'] = SchemaForm(instance=self.object)
            context['schema_details_form'] = SchemaDetailsFormSet(instance=self.object)
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        schema_details_form = context['schema_details_form']
        with transaction.atomic():
            self.object = form.save()
            if schema_details_form.is_valid():
                schema_details_form.instance = self.object
                schema_details_form.save()
        return super(SchemaEdit, self).form_valid(form)


class SchemaDelete(LoginRequiredMixin, DeleteView):
    model = Schema
    template_name = 'main/delete_confirm_schema.html'
    success_url = reverse_lazy('main:list_schemas')


class DatasetList(LoginRequiredMixin, ListView):
    model = Dataset
    template_name = 'main/list_datasets.html'
    fields = ['created_at', ]

    def get_queryset(self):
        self.schema = get_object_or_404(Schema, id=self.kwargs['pk'])
        return Dataset.objects.filter(schema=self.schema)

    def get_context_data(self, **kwargs):
        context = super(DatasetList, self).get_context_data(**kwargs)
        for item in context['object_list']:
            item.status = AsyncResult(item.task_id).state
            item.url = get_download_link(item)
        context['schema_id'] = self.kwargs['pk']
        return context


@login_required
def create_dataset(request):
    print(request.POST)
    if request.method == 'POST':
        form = DatasetForm(request.POST)
        if form.is_valid():
            generate_data.delay(request.POST['schema_id'], request.POST['rows'])
            # return redirect(f'/schemas/list_datasets/{request.POST["schema_id"]}/',)
            return redirect('main:list_schemas')
    else:
        form = DatasetForm()
    return render(request, 'main/list_datasets.html', {'form': form})

def get_download_link(file_record):
    s3_client = boto3.client('s3', aws_access_key_id=AWS_ACCESS_KEY_ID,
                             aws_secret_access_key=AWS_SECRET_ACCESS_KEY,
                             config=Config(signature_version=AWS_S3_SIGNATURE_VERSION,
                                           region_name=REGION_NAME))
    return s3_client.generate_presigned_url('get_object',
                                            Params={'Bucket': S3_BUCKET, 'Key': file_record.file.name},
                                            ExpiresIn=None)

csv_generator/templates/main/base.html
<!doctype  html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{% static 'main/css/styles.css' %}">
        <title>Fake CSV</title>
    </head>
    <body>
        <div class="container">
            <div class="header">
                <div class="header-left">
                    <p id="header-title">FakeCSV</p>
                    <a href="{% url 'main:list_schemas' %}">Schemas</a>
                </div>
                <div class="header-right">
                    <p>Hello, {{ user.username }}</p>
                    <a class="header-link" href="{% url 'admin:logout' %}">Logout</a>
                </div>
            </div>
            {% block main %}
            {% endblock %}
        </div>
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
            integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
            crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
            integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
            crossorigin="anonymous"></script>
        <script src="{% static 'main/js/schema_form_script.js' %}"></script>
    </body>
</html>

csv_generator/templates/main/delete_confirm_schema.html
{% extends 'main/base.html' %}
{% block main %}
    <div class="category_delete">
        <div class="h1">Are you sure?</div>
        <form action="{% url 'main:delete_schema' object.pk %}" method="post">
            {% csrf_token %}
            <input class="btn btn-danger" type="submit" value="Delete">
        </form>
        <button class="btn btn-success">
            <a href="{% url 'main:list_schemas' %}">Cancel</a>
        </button>
    </div>
{% endblock %}

csv_generator/templates/main/list_datasets.html
{% extends 'main/base.html' %}
{% load static %}

{% block main %}
    <div class="content-header">
        <div class="content-topic">Data sets</div>
        <form id="generate-data" action="{% url 'main:create_dataset' %}" method="POST">
            {% csrf_token %}
            <label for="rows">Rows:</label>
            <input name="rows" type="text" value="500">
            <input type="hidden" value="{{ schema_id }}" name="schema_id">
            <button class="green-button" type="submit">Generate data</button>
        </form>
    </div>
    <table class="table table-bordered">
        <tr>
            <th>#</th>
            <th>Created</th>
            <th>Status</th>
            <th>Actions</th>
        </tr>
        {% for item in object_list %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ item.created_at|date:"Y-m-d" }}</a></td>
                {% if item.status == 'SUCCESS' %}
                    <td><img src="{% static 'main/img/label-ready.png' %}" alt="ready"></td>
                {% else %}
                    <td><img src="{% static 'main/img/label-processing.png' %}" alt="processing"></td>
                {% endif %}
                <td>
                    <a href="{{ item.url }}" download>Download</a>
                </td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}

csv_generator/templates/main/list_schemas.html
{% extends 'main/base.html' %}
{% load static %}

{% block main %}
    <div class="content-header">
        <div class="content-topic">Data schemas</div>
        <a class="green-link-button" href="{% url 'main:create_schema' %}">New schema</a>
    </div>
    <table class="table table-bordered">
        <tr>
            <th>#</th>
            <th>Title</th>
            <th>Modified</th>
            <th>Actions</th>
        </tr>
        {% for item in object_list %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td><a href="{% url 'main:edit_schema' item.pk %}">{{ item.name }}</a></td>
                <td>{{ item.updated_at|date:"Y-m-d" }}</td>
                <td>
                    <a href="{% url 'main:edit_schema' item.pk %}">Edit scheme</a>
                    <a href="{% url 'main:delete_schema' item.pk %}" class="red-link">Delete</a>
                    <a href="{% url 'main:list_datasets' item.pk %}">List datasets</a>
                </td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}

csv_generator/templates/main/schema_form.html
{% extends 'main/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block main %}
    <div class="content">
        <div class="content-topic">New schema</div>
        <form id="schema-form" action="" method="post">
            {% csrf_token %}
            <button class="blue-button" type="submit" style="float: right;">Submit</button>
            {{ form|crispy }}
            <div class="content-topic">Schema columns</div>
            {{ schema_details_form.management_form }}
            {% for field in schema_details_form %}
                <div class="column-form">
                    {{ field.label_tag }}{{ field }}
                </div>
            {% endfor %}
            <button class="blue-button" id="add-column" type="button">Add column</button>
        </form>
    </div>
{% endblock %}